x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  api:
    container_name: api-story-maker
    build:
      context: .
      dockerfile: ./DockerfileDev
    command: >
      sh -c "yarn tsc && yarn dev"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./storage:/storage
      - ./jest.config.json:/app/jest.config.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
      - ./.eslintrc.cjs:/app/.eslintrc.cjs
      - ./containers/api/.ash_history:/home/node/.ash_history
    env_file:
      - .env
    logging: *default-logging
    ports:
      - 3000:3000
    links:
      - postgres
    networks:
      - choose_your_own_adventure_network

  postgres:
    image: postgres:latest
    container_name: story-maker-db
    volumes:
      - postgres_data:/var/lib/postgres
      - ./containers/postgres/initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    logging: *default-logging
    networks:
      - choose_your_own_adventure_network

  liquibase:
    image: liquibase/liquibase:4.25
    command: /liquibase/liquibase --url="jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?currentSchema=story_maker&ssl=true&sslmode=require&sslrootcert=$POSTGRES_CERT_FILE" --changeLogFile=changelog/changelog.xml --logLevel=info update --userName=$POSTGRES_USER --password=$POSTGRES_PASSWORD
    env_file:
      - .env
    links:
      - postgres
    volumes:
      - ./src/database/liquibase.xml:/liquibase/changelog/changelog.xml
      - ./src/database/scripts:/liquibase/changelog/scripts
      - ./certificates/postgres-ca.cert:/liquibase/postgres-ca.cert
    networks:
      - choose_your_own_adventure_network

  liquibase-local:
    image: liquibase/liquibase:4.25
    command: |
      liquibase --url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB --changeLogFile=changelog/changelog.xml --logLevel=info update --userName=$POSTGRES_USER --password=$POSTGRES_PASSWORD
    env_file:
      - .env
    links:
      - postgres
    volumes:
      - ./src/database/liquibase.xml:/liquibase/changelog/changelog.xml
      - ./src/database/scripts:/liquibase/changelog/scripts
    networks:
      - choose_your_own_adventure_network


volumes:
  postgres_data:

networks:
  choose_your_own_adventure_network:
