version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  api:
    container_name: api-story-maker
    build:
      context: .
      dockerfile: ./DockerfileDev
    command: >
      sh -c "yarn tsc && yarn nodemon dist/index.js"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./storage:/storage
      - ./tsconfig.json:/app/tsconfig.json
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
    env_file:
      - .env
    logging: *default-logging
    ports:
      - 3000:3000
    links:
      - postgres
    networks:
      - choose_your_own_adventure_network

  postgres:
    image: postgres:latest
    container_name: story-maker-db
    volumes:
      - postgres_data:/var/lib/postgres
      - ./pg-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    logging: *default-logging
    networks:
      - choose_your_own_adventure_network

volumes:
  postgres_data:

networks:
  choose_your_own_adventure_network:
