apiVersion: v1
kind: Service
metadata:
  name: story-maker-api
spec:
  # GCE Ingress has to be 'NodePort' or 'LoadBalancer'
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: story-maker-api

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: story-maker-api
spec:
  serviceName: story-maker-api
  replicas: 1
  selector:
    matchLabels:
      app: story-maker-api
  template:
    metadata:
      labels:
        app: story-maker-api
    spec:
      containers:
        - name: story-maker-api
          image: jotaram/story-maker-api:1.0.12
          ports:
            - containerPort: 80
          env:
            - name: SECRET
              value: "secret"
            - name: PUBLIC_PATH
              value: "/"
            - name: POSTGRES_USER
              value: "story_maker_user"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "story_maker"
            - name: POSTGRES_HOST
              value: "private-db-postgresql-prod-do-user-11639445-0.b.db.ondigitalocean.com"
            - name: POSTGRES_PORT
              value: "25060"
            - name: POSTGRES_CA
              valueFrom:
                secretKeyRef:
                  name: postgres-ca
                  key: certificate
            - name: ENVIRONMENT
              value: "production"
            - name: DO_SPACES_ENDPOINT
              value: "nyc3.digitaloceanspaces.com"
            - name: DO_SPACES_KEY
              value: "DO0093A6LTGME7YUUXMX"
            - name: DO_SPACES_SECRET
              value: "dbGnDBKH1nunYf3mz6EgY0GBTj+twGgDhu1ANM5c7g4"
            - name: DO_SPACES_NAME
              value: "jrojaspin"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-story-maker-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - story-maker-api.jrojaspin.com.ar
      secretName: hello-kubernetes-tls-story-maker-api
  rules:
    - host: story-maker-api.jrojaspin.com.ar
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: story-maker-api
                port:
                  number: 80
