apiVersion: v1
kind: Service
metadata:
  name: story-maker-api
spec:
  # GCE Ingress has to be 'NodePort' or 'LoadBalancer'
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: story-maker-api

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: story-maker-api
spec:
  serviceName: story-maker-api
  replicas: 1
  selector:
    matchLabels:
      app: story-maker-api
  template:
    metadata:
      labels:
        app: story-maker-api
    spec:
      containers:
        - name: story-maker-api
          image: "$DOCKER_IMAGE_VERSION"
          ports:
            - containerPort: 80
          env:
            - name: SECRET
              value: "$API_SECRET"
            - name: PUBLIC_PATH
              value: "/"
            - name: POSTGRES_USER
              value: "$POSTGRES_USER"
            - name: POSTGRES_PASSWORD
              value: "$POSTGRES_PASSWORD"
            - name: POSTGRES_DB
              value: "$POSTGRES_DB"
            - name: POSTGRES_HOST
              value: "$POSTGRES_HOST"
            - name: POSTGRES_PORT
              value: "$POSTGRES_PORT"
            - name: POSTGRES_CA
              valueFrom:
                secretKeyRef:
                  name: postgres-ca
                  key: certificate
            - name: DO_SPACES_ENDPOINT
              value: "$DO_SPACES_ENDPOINT"
            - name: DO_SPACES_KEY
              value: "$DO_SPACES_KEY"
            - name: DO_SPACES_SECRET
              value: "$DO_SPACES_SECRET"
            - name: DO_SPACES_NAME
              value: "$DO_SPACES_NAME"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-story-maker-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - story-maker-api.jrojaspin.com.ar
      secretName: hello-kubernetes-tls-story-maker-api
  rules:
    - host: story-maker-api.jrojaspin.com.ar
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: story-maker-api
                port:
                  number: 80
