name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ 'main' ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build app
        run: yarn build
