name: CICD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            jotaram/story-maker-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: "Init certs"
        env:
          POSTGRES_CERT: ${{ secrets.POSTGRES_CERT }}
        run: |
          echo "$POSTGRES_CERT" > $GITHUB_WORKSPACE/tmp_db_cert.cert

      - name: "Add IP"
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "add"
          database_id: ${{ secrets.POSTGRES_DATABASE_INSTANCE_ID }}
          digitalocean_token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: "Update database"
        uses: liquibase-github-actions/update@v4.25.1
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        with:
          changelogFile: "$GITHUB_WORKSPACE/src/database/liquibase.xml"
          url: "jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?currentSchema=story_maker&ssl=true&sslmode=require&sslrootcert=$GITHUB_WORKSPACE/tmp_db_cert.cert"
          password: ${{ secrets.POSTGRES_PASSWORD }}
          username: ${{ secrets.POSTGRES_USER }}

      - name: "Remove IP"
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "remove"
          database_id: ${{ secrets.POSTGRES_DATABASE_INSTANCE_ID }}
          digitalocean_token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: "Remove certs"
        run: rm $GITHUB_WORKSPACE/tmp_db_cert.cert

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DO_K8S_CLUSTER_NAME }}

      - name: Deploy to DigitalOcean K8S
        run: |
          export SECRET=${{ secrets.API_SECRET }}
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          export DO_SPACES_ENDPOINT=${{ secrets.DO_SPACES_ENDPOINT }}
          export DO_SPACES_KEY=${{ secrets.DO_SPACES_KEY }}
          export DO_SPACES_SECRET=${{ secrets.DO_SPACES_SECRET }}
          export DO_SPACES_NAME=${{ secrets.DO_SPACES_NAME }}
          sh $GITHUB_WORKSPACE/k8s/install.sh
