name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            jotaram/story-maker-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          keys: tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DO_K8S_CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          export SECRET=${{ secrets.API_SECRET }}
          export PUBLIC_PATH=${{ secrets.PUBLIC_PATH }}
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          export DO_SPACES_ENDPOINT=${{ secrets.DO_SPACES_ENDPOINT }}
          export DO_SPACES_KEY=${{ secrets.DO_SPACES_KEY }}
          export DO_SPACES_SECRET=${{ secrets.DO_SPACES_SECRET }}
          export DO_SPACES_NAME=${{ secrets.DO_SPACES_NAME }}
          export DOCKER_IMAGE_VERSION=$(echo "${{ steps.meta.outputs.DOCKER_METADATA_OUTPUT_TAGS }}")
          sh $GITHUB_WORKSPACE/k8s/install.sh
